# Generated by Django 5.1.4 on 2024-12-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instahyre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='spam',
        ),
        migrations.AddField(
            model_name='profile',
            name='spam_count',
            field=models.IntegerField(default=0),
        ),
    ]
